[window]
decorations = "buttonless"
option_as_alt = "Both"
opacity = 0.7
blur = true
[font]
normal = { style = "Regular", family = "JetBrainsMono Nerd Font" }
bold = { style = "Bold", family = "JetBrainsMono Nerd Font" }
italic = { style = "Italic", family = "JetBrainsMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "JetBrainsMono Nerd Font" }
size = 18
[env]
TERM = "xterm-256color"
[mouse]
hide_when_typing = true
[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'
