[window]
decorations = "buttonless"
# opacity = 0.9
# blur = true
option_as_alt = "Both"
[font]
normal = { style = "Regular", family = "JetBrainsMono Nerd Font" }
bold = { style = "Bold", family = "JetBrainsMono Nerd Font" }
italic = { style = "Italic", family = "JetBrainsMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "JetBrainsMono Nerd Font" }
size = 16
[env]
TERM = "xterm-256color"
[mouse]
hide_when_typing = true
# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'
