[shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l"]
[window]
decorations = "buttonless"
option_as_alt = "Both"
[font]
normal = { style = "Regular", family = "JetBrainsMono Nerd Font" }
bold = { style = "Bold", family = "JetBrainsMono Nerd Font" }
italic = { style = "Italic", family = "JetBrainsMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "JetBrainsMono Nerd Font" }
size = 16
[env]
TERM = "xterm-256color"
[mouse]
hide_when_typing = true

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'
# Normal colors
[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

# Bright colors
[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'
